name: Haskell CI

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.0', '8.2', '8.4']
    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
    - name: Build
      run: cabal build
    - name: Run tests
      run: cabal run test --enable-tests
